-- USERS & AUTHENTICATION
CREATE TABLE Users (
    UserId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Email NVARCHAR(255) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(512) NOT NULL,
    Role NVARCHAR(50) NOT NULL DEFAULT 'User', -- User, Admin, etc.
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

-- WORKFLOWS
CREATE TABLE Workflows (
    WorkflowId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    Version INT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT FK_Workflows_Users FOREIGN KEY (UserId) REFERENCES Users(UserId)
);

-- WORKFLOW TRIGGERS
CREATE TABLE WorkflowTriggers (
    TriggerId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    WorkflowId UNIQUEIDENTIFIER NOT NULL,
    TriggerType NVARCHAR(100) NOT NULL, -- Webhook, Schedule, Manual, etc.
    Config NVARCHAR(MAX) NOT NULL,      -- JSON configuration
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT FK_WorkflowTriggers_Workflows FOREIGN KEY (WorkflowId) REFERENCES Workflows(WorkflowId)
);

-- WORKFLOW STEPS (ACTIONS)
CREATE TABLE WorkflowSteps (
    StepId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    WorkflowId UNIQUEIDENTIFIER NOT NULL,
    StepOrder INT NOT NULL,
    StepType NVARCHAR(100) NOT NULL, -- HTTP, Email, Delay, etc.
    Name NVARCHAR(255) NOT NULL,
    Config NVARCHAR(MAX) NOT NULL,   -- JSON structure (endpoint, headers, etc.)
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT FK_WorkflowSteps_Workflows FOREIGN KEY (WorkflowId) REFERENCES Workflows(WorkflowId)
);

-- WORKFLOW EXECUTION HISTORY
CREATE TABLE WorkflowRuns (
    RunId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    WorkflowId UNIQUEIDENTIFIER NOT NULL,
    TriggeredBy NVARCHAR(100) NOT NULL, -- Webhook, Manual, etc.
    Status NVARCHAR(50) NOT NULL DEFAULT 'Pending', -- Pending, Success, Failed
    StartedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    CompletedAt DATETIME2 NULL,

    CONSTRAINT FK_WorkflowRuns_Workflows FOREIGN KEY (WorkflowId) REFERENCES Workflows(WorkflowId)
);

-- STEP EXECUTION PER RUN
CREATE TABLE WorkflowStepRuns (
    StepRunId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    RunId UNIQUEIDENTIFIER NOT NULL,
    StepId UNIQUEIDENTIFIER NOT NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Pending', -- Pending, Success, Failed
    StartedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    CompletedAt DATETIME2 NULL,
    Output NVARCHAR(MAX) NULL, -- JSON result / response payload

    CONSTRAINT FK_WorkflowStepRuns_Runs FOREIGN KEY (RunId) REFERENCES WorkflowRuns(RunId),
    CONSTRAINT FK_WorkflowStepRuns_Steps FOREIGN KEY (StepId) REFERENCES WorkflowSteps(StepId)
);

-- LOGS (EXECUTION-LEVEL)
CREATE TABLE ExecutionLogs (
    LogId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    RunId UNIQUEIDENTIFIER NOT NULL,
    StepId UNIQUEIDENTIFIER NULL,
    LogLevel NVARCHAR(20) NOT NULL, -- Info, Warning, Error
    Message NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT FK_Logs_Runs FOREIGN KEY (RunId) REFERENCES WorkflowRuns(RunId),
    CONSTRAINT FK_Logs_Steps FOREIGN KEY (StepId) REFERENCES WorkflowSteps(StepId)
);

-- OPTIONAL: API KEYS (for external triggers or clients)
CREATE TABLE ApiKeys (
    ApiKeyId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    KeyHash NVARCHAR(512) NOT NULL,
    Name NVARCHAR(255) NOT NULL,
    IsRevoked BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ExpiresAt DATETIME2 NULL,

    CONSTRAINT FK_ApiKeys_Users FOREIGN KEY (UserId) REFERENCES Users(UserId)
);
